services:
    php-fpm:
        build:
            context: ./docker/php-fpm
        expose:
            - '9000'
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
        restart: always
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - '${APP_PORT:-443}:443'
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${LETS_ENCRYPT_PATH}:/etc/letsencrypt
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - sail
        depends_on:
            - php-fpm
        restart: always
    mariadb:
        image: 'mariadb:10'
        expose:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: 'localhost'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            TZ: 'Asia/Jakarta'
        volumes:
            - './sail-mariadb:/var/lib/mysql'
        networks:
            - sail
        restart: always
    npm:
        image: node:latest
        entrypoint: ['npm']
        working_dir: /var/www
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
networks:
    sail:
        driver: bridge
